package essp.usg.model.readonly.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 01 17:03:38 PKT 2018
// ---------------------------------------------------------------------
public interface VOLoginAccessApprovalHeaderRow extends Row {
    void approveRequest(int reqHeaderID);
}

