package essp.usg.model.entity_objects;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 20 10:09:52 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustEmployeeOvertimeImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        OvertimeId,
        OvertimeDate,
        OvertimePayMonth,
        EmployeeId,
        OvertimeHours,
        OvertimeDept,
        CreationDate,
        UpdationDate,
        CreatedBy,
        UpdatedBy,
        VersionNumber,
        UserIpAddress,
        PayYear;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int OVERTIMEID = AttributesEnum.OvertimeId.index();
    public static final int OVERTIMEDATE = AttributesEnum.OvertimeDate.index();
    public static final int OVERTIMEPAYMONTH = AttributesEnum.OvertimePayMonth.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int OVERTIMEHOURS = AttributesEnum.OvertimeHours.index();
    public static final int OVERTIMEDEPT = AttributesEnum.OvertimeDept.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int USERIPADDRESS = AttributesEnum.UserIpAddress.index();
    public static final int PAYYEAR = AttributesEnum.PayYear.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustEmployeeOvertimeImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("essp.usg.model.entity_objects.CustEmployeeOvertime");
    }

    /**
     * Gets the attribute value for OvertimeId, using the alias name OvertimeId.
     * @return the value of OvertimeId
     */
    public BigDecimal getOvertimeId() {
        return (BigDecimal) getAttributeInternal(OVERTIMEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OvertimeId.
     * @param value value to set the OvertimeId
     */
    public void setOvertimeId(BigDecimal value) {
        setAttributeInternal(OVERTIMEID, value);
    }

    /**
     * Gets the attribute value for OvertimeDate, using the alias name OvertimeDate.
     * @return the value of OvertimeDate
     */
    public Timestamp getOvertimeDate() {
        return (Timestamp) getAttributeInternal(OVERTIMEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OvertimeDate.
     * @param value value to set the OvertimeDate
     */
    public void setOvertimeDate(Timestamp value) {
        setAttributeInternal(OVERTIMEDATE, value);
    }

    /**
     * Gets the attribute value for OvertimePayMonth, using the alias name OvertimePayMonth.
     * @return the value of OvertimePayMonth
     */
    public BigDecimal getOvertimePayMonth() {
        return (BigDecimal) getAttributeInternal(OVERTIMEPAYMONTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for OvertimePayMonth.
     * @param value value to set the OvertimePayMonth
     */
    public void setOvertimePayMonth(BigDecimal value) {
        setAttributeInternal(OVERTIMEPAYMONTH, value);
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for OvertimeHours, using the alias name OvertimeHours.
     * @return the value of OvertimeHours
     */
    public BigDecimal getOvertimeHours() {
        return (BigDecimal) getAttributeInternal(OVERTIMEHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for OvertimeHours.
     * @param value value to set the OvertimeHours
     */
    public void setOvertimeHours(BigDecimal value) {
        setAttributeInternal(OVERTIMEHOURS, value);
    }

    /**
     * Gets the attribute value for OvertimeDept, using the alias name OvertimeDept.
     * @return the value of OvertimeDept
     */
    public String getOvertimeDept() {
        return (String) getAttributeInternal(OVERTIMEDEPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OvertimeDept.
     * @param value value to set the OvertimeDept
     */
    public void setOvertimeDept(String value) {
        setAttributeInternal(OVERTIMEDEPT, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for UpdationDate, using the alias name UpdationDate.
     * @return the value of UpdationDate
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the value of VersionNumber
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Gets the attribute value for UserIpAddress, using the alias name UserIpAddress.
     * @return the value of UserIpAddress
     */
    public String getUserIpAddress() {
        return (String) getAttributeInternal(USERIPADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIpAddress.
     * @param value value to set the UserIpAddress
     */
    public void setUserIpAddress(String value) {
        setAttributeInternal(USERIPADDRESS, value);
    }

    /**
     * Gets the attribute value for PayYear, using the alias name PayYear.
     * @return the value of PayYear
     */
    public BigDecimal getPayYear() {
        return (BigDecimal) getAttributeInternal(PAYYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for PayYear.
     * @param value value to set the PayYear
     */
    public void setPayYear(BigDecimal value) {
        setAttributeInternal(PAYYEAR, value);
    }


    /**
     * @param overtimeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal overtimeId) {
        return new Key(new Object[] { overtimeId });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        switch(operation){
        case DML_INSERT:
            setCreatedBy(new BigDecimal(ADFContext.getCurrent().getSessionScope().get("sess_empcode").toString()));
            setUpdatedBy(new BigDecimal(ADFContext.getCurrent().getSessionScope().get("sess_empcode").toString()));
        break;
        case DML_UPDATE:
            setUpdatedBy(new BigDecimal(ADFContext.getCurrent().getSessionScope().get("sess_empcode").toString()));
            break;
        }
        super.doDML(operation, e);
    }
}

