package essp.usg.model.application_modules.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 20 14:39:26 PKT 2018
// ---------------------------------------------------------------------
public interface usgesspappmodule extends ApplicationModule {
    void processOvertime();

    void submitITAccessReq();

    void getActiveInternetReq();
}

