package essp.usg.model.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 16 12:25:40 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MonthCodesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MonthCodesImpl() {
    }
}

