package essp.usg.model.readonly;


import essp.usg.model.readonly.common.VOLoginAccessApprovalHeaderRow;

import java.math.BigDecimal;

import java.sql.CallableStatement;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 01 17:00:33 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOLoginAccessApprovalHeaderRowImpl extends ViewRowImpl implements VOLoginAccessApprovalHeaderRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovalHistoryId,
        ReqHeaderId,
        UserId,
        Active,
        Status,
        EmployeeName,
        Designation,
        VOLoginAccessApprovalLines;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPROVALHISTORYID = AttributesEnum.ApprovalHistoryId.index();
    public static final int REQHEADERID = AttributesEnum.ReqHeaderId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int VOLOGINACCESSAPPROVALLINES = AttributesEnum.VOLoginAccessApprovalLines.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VOLoginAccessApprovalHeaderRowImpl() {
    }


    public void approveRequest(int reqHeaderID){
        CallableStatement cst = null;
        try{
            cst = getDBTransaction().createCallableStatement("{call USTMS.cust_approve_login_access(?)}", 0);
        
            cst.setInt(1, reqHeaderID);
            
            cst.executeUpdate();
            System.out.println();
            
        }catch(Exception ex){
            ex.printStackTrace();
            
        }
    }
}

