package essp.usg.model.updatable.common;

import java.sql.Date;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 30 15:52:39 PKT 2018
// ---------------------------------------------------------------------
public interface VOHODLeavesPortalRow extends Row {
    void sendNotification(String action, String empCode, String emailID, Date fromDate, String name);
}

