package essp.usg.model.updatable.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 17 09:57:39 PKT 2018
// -------------------OVERRIDE THESE METHODS IN THE ROW IMPLEMENTATION CLASS. THIS IS TO EXPOSE THIS METHOD TO CLIENT SO THAT WE CAN USE IT IN OTHER PLROJECT----------------------------------------
public interface VOLeavesPortalRow extends Row {
    int submitLeaveAction();
}

