package essp.usg.model.updatable;

import essp.usg.model.entity_objects.XxItAccessReqLinesImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 30 15:10:25 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOXxItLoginAccessReqLinesRowImpl extends ViewRowImpl {


    public static final int ENTITY_XXITACCESSREQLINES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ReqLineId,
        ReqHeaderId,
        AccessType,
        AccessObject,
        OtherAccessObject,
        CreationDate,
        CreatedBy,
        UpdationDate,
        UpdatedBy,
        VersionNumber,
        Justification;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int REQLINEID = AttributesEnum.ReqLineId.index();
    public static final int REQHEADERID = AttributesEnum.ReqHeaderId.index();
    public static final int ACCESSTYPE = AttributesEnum.AccessType.index();
    public static final int ACCESSOBJECT = AttributesEnum.AccessObject.index();
    public static final int OTHERACCESSOBJECT = AttributesEnum.OtherAccessObject.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATIONDATE = AttributesEnum.UpdationDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int JUSTIFICATION = AttributesEnum.Justification.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VOXxItLoginAccessReqLinesRowImpl() {
    }

    /**
     * Gets XxItAccessReqLines entity object.
     * @return the XxItAccessReqLines
     */
    public XxItAccessReqLinesImpl getXxItAccessReqLines() {
        return (XxItAccessReqLinesImpl) getEntity(ENTITY_XXITACCESSREQLINES);
    }

    /**
     * Gets the attribute value for REQ_LINE_ID using the alias name ReqLineId.
     * @return the REQ_LINE_ID
     */
    public BigDecimal getReqLineId() {
        return (BigDecimal) getAttributeInternal(REQLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_LINE_ID using the alias name ReqLineId.
     * @param value value to set the REQ_LINE_ID
     */
    public void setReqLineId(BigDecimal value) {
        setAttributeInternal(REQLINEID, value);
    }

    /**
     * Gets the attribute value for REQ_HEADER_ID using the alias name ReqHeaderId.
     * @return the REQ_HEADER_ID
     */
    public BigDecimal getReqHeaderId() {
        return (BigDecimal) getAttributeInternal(REQHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_HEADER_ID using the alias name ReqHeaderId.
     * @param value value to set the REQ_HEADER_ID
     */
    public void setReqHeaderId(BigDecimal value) {
        setAttributeInternal(REQHEADERID, value);
    }

    /**
     * Gets the attribute value for ACCESS_TYPE using the alias name AccessType.
     * @return the ACCESS_TYPE
     */
    public BigDecimal getAccessType() {
        return (BigDecimal) getAttributeInternal(ACCESSTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCESS_TYPE using the alias name AccessType.
     * @param value value to set the ACCESS_TYPE
     */
    public void setAccessType(BigDecimal value) {
        setAttributeInternal(ACCESSTYPE, value);
    }

    /**
     * Gets the attribute value for ACCESS_OBJECT using the alias name AccessObject.
     * @return the ACCESS_OBJECT
     */
    public BigDecimal getAccessObject() {
        return (BigDecimal) getAttributeInternal(ACCESSOBJECT);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCESS_OBJECT using the alias name AccessObject.
     * @param value value to set the ACCESS_OBJECT
     */
    public void setAccessObject(BigDecimal value) {
        setAttributeInternal(ACCESSOBJECT, value);
    }

    /**
     * Gets the attribute value for OTHER_ACCESS_OBJECT using the alias name OtherAccessObject.
     * @return the OTHER_ACCESS_OBJECT
     */
    public String getOtherAccessObject() {
        return (String) getAttributeInternal(OTHERACCESSOBJECT);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_ACCESS_OBJECT using the alias name OtherAccessObject.
     * @param value value to set the OTHER_ACCESS_OBJECT
     */
    public void setOtherAccessObject(String value) {
        setAttributeInternal(OTHERACCESSOBJECT, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATION_DATE using the alias name UpdationDate.
     * @return the UPDATION_DATE
     */
    public Timestamp getUpdationDate() {
        return (Timestamp) getAttributeInternal(UPDATIONDATE);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public BigDecimal getVersionNumber() {
        return (BigDecimal) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(BigDecimal value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for JUSTIFICATION using the alias name Justification.
     * @return the JUSTIFICATION
     */
    public String getJustification() {
        return (String) getAttributeInternal(JUSTIFICATION);
    }

    /**
     * Sets <code>value</code> as attribute value for JUSTIFICATION using the alias name Justification.
     * @param value value to set the JUSTIFICATION
     */
    public void setJustification(String value) {
        setAttributeInternal(JUSTIFICATION, value);
    }
    
    @Override
    protected void create(AttributeList attributeList) {
        setAccessType(new BigDecimal(1));
        super.create(attributeList);
    }
}

